name: Build and Deploy Dockerized Flask App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub using credentials stored in GitHub Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Determine version (tag or commit SHA)
    - name: Get the version
      id: version
      run: |
        VERSION=$(git describe --tags --always || echo "latest")
        echo "::set-output name=version::$VERSION"

    # Step 5: Build the Docker image with the dynamic version
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ steps.version.outputs.version }} .

    # Step 6: Push the Docker image to Docker Hub with the dynamic version
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ steps.version.outputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Deploy the Dockerized app on a remote server (via SSH)
    - name: Deploy to Remote Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ steps.version.outputs.version }}
          docker stop flask-app || true
          docker rm flask-app || true
          docker run -d -p 80:4000 --name flask-app ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ steps.version.outputs.version }}
