name: Build and Deploy Dockerized Flask App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub using credentials stored in GitHub Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Extract the Git commit SHA and set the version number
    - name: Extract Git Commit SHA
      id: git-info
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    # Step 5: Build the Docker image with a dynamic version tag
    - name: Build Docker image
      run: |
        IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/flask-app:${{ steps.git-info.outputs.sha_short }}
        docker build -t $IMAGE_TAG .
        docker tag $IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

    # Step 6: Push both the versioned and latest Docker images to Docker Hub
    - name: Push Docker images to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ steps.git-info.outputs.sha_short }}
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Remote Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ steps.git-info.outputs.sha_short }}
          docker stop flask-app || true
          docker rm flask-app || true
          docker run -d -p 80:4000 --name flask-app ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ steps.git-info.outputs.sha_short }}
