name: Deploy App

on:
  push:
    branches:
      - main # Trigger the workflow on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t fajobi13/pythonproject1-app:latest .
        docker push fajobi13/pythonproject1-app:latest

    - name: Deploy Docker container
      run: docker run -d -p 4000:4000 fajobi13/pythonproject1-app:latest